{
 "title": "RoadRunner JOBS dashboard",
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "go_info" } }
  ]
 },
 "panels": [
  {
   "title": "RR uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rr_http_uptime_seconds{instance=\"$server\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$server\"}",
     "legendFormat": "RR memory"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$server\"}",
     "legendFormat": "Green threads count"
    }
   ]
  },
  {
   "title": "Jobs workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_jobs_total_workers", "legendFormat": "TOTAL" },
    {
     "expr": "rr_jobs_workers_ready{instance=\"$server\"}",
     "legendFormat": "READY"
    },
    {
     "expr": "rr_jobs_workers_working{instance=\"$server\"}",
     "legendFormat": "WORKING"
    },
    {
     "expr": "rr_jobs_workers_invalid{instance=\"$server\"}",
     "legendFormat": "INVALID"
    }
   ]
  },
  {
   "title": "Workers total memory [JOBS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_jobs_workers_memory_bytes{instance=\"$server\"}/1024000)",
     "legendFormat": "Workers total memory used"
    }
   ]
  },
  {
   "title": "Memory by worker [JOBS]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rr_jobs_worker_memory_bytes{instance=\"$server\"}",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  },
  {
   "title": "JOBS Ok  rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(rr_jobs_jobs_ok{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "JOBS errors rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(rr_jobs_jobs_err{instance=\"$server\"}[5m])"
    }
   ]
  }
 ]
}